In [89]:
#Import libraries

In [90]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree

In [91]:
#Read data

In [92]:
df = pd.read_csv("heart_attack_prediction_dataset.csv")

In [93]:
#Cleaning data

In [94]:
df = df.drop(columns=["Patient ID"])
df

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,67,Male,208,158/88,72,0,0,1,0,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,21,Male,389,165/93,98,1,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,21,Female,324,174/99,72,1,0,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,84,Male,383,163/100,73,1,1,1,0,1,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,66,Male,318,91/88,93,1,1,1,1,0,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,Male,121,94/76,61,1,1,1,0,1,...,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,28,Female,120,157/102,73,1,0,0,1,0,...,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,47,Male,250,161/75,105,0,1,1,1,1,...,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,36,Male,178,119/67,60,1,0,1,0,0,...,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,25,Female,356,138/67,75,1,1,0,0,1,...,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [95]:
systolic = []
diastolic = []
for i in df["Blood Pressure"]:
  split_data = i.split("/")
  systolic.append(split_data[0])
  diastolic.append(split_data[1])

In [96]:
bp_loc = df.columns.get_loc("Blood Pressure")

In [97]:
df.insert(bp_loc,"Systolic", systolic)
df.insert(bp_loc,"Diastolic", diastolic)
df

,Age,Sex,Cholesterol,Diastolic,Systolic,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,67,Male,208,88,158,158/88,72,0,0,1,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,21,Male,389,93,165,165/93,98,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,21,Female,324,99,174,174/99,72,1,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,84,Male,383,100,163,163/100,73,1,1,1,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,66,Male,318,88,91,91/88,93,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,Male,121,76,94,94/76,61,1,1,1,...,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,28,Female,120,102,157,157/102,73,1,0,0,...,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,47,Male,250,75,161,161/75,105,0,1,1,...,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,36,Male,178,67,119,119/67,60,1,0,1,...,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,25,Female,356,67,138,138/67,75,1,1,0,...,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [98]:
df = df.drop(columns=["Blood Pressure"])

In [99]:
#Converting strings to 0s and 1s
#Male -> 0
#Female -> 1
#unhealthy -> 0
#healthy -> 1
#average = 2
#Also removing other columns
df = df.drop(columns=["Hemisphere", "Continent", "Country"])
df = df.replace(to_replace=["Male"], value=0)
df = df.replace(to_replace=["Female"], value=1)
df = df.replace(to_replace=["Unhealthy"], value=0)
df = df.replace(to_replace=["Healthy"], value=1)
df = df.replace(to_replace=["Average"], value=2)

In [100]:
df.to_csv("cleaned_data.csv")

In [101]:
#Splitting into input and output dataset

In [102]:
X = df.drop(columns=["Heart Attack Risk"])
y = df["Heart Attack Risk"]

In [103]:
#Splitting into test and train datasets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [104]:
#Training model and initalizing it
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [105]:
#Making predictions
pred = model.predict(X_test)

In [106]:
#Calculating accuracy
score = accuracy_score(y_test, pred)
score

0.5142531356898518

In [109]:
custom_pred = model.predict([[90,0,358,73,102,84,0,0,1,0,1,4.098177090985471,1,0,0,7,0.6273560009569512,190450,28.885810606590454,284,4,10]])

C:\Users\yusuf\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [110]:
custom_pred

array([1], dtype=int64)